.services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: martybarty/drako-sync:latest
    ports:
      - "8081:8080"
    environment:
      - WEB_PORT=${WEB_PORT}
      - WEB_HOST=${WEB_HOST}
      - INIT_PROMPT=${INIT_PROMPT}

      - OPEN_AI_KEY=${OPEN_AI_KEY}
      - RPC_URL=${RPC_URL}
      - GAME_CONTRACT_ADDRESS=${GAME_CONTRACT_ADDRESS}
      - ADMIN_ADDRESS=${ADMIN_ADDRESS}

      - PRIVATE_KEY=${PRIVATE_KEY}
      - PUBLIC_KEY=${PUBLIC_KEY}
    #    volumes:
    #      - ./backend:/app
    #      - .:/app
    restart: unless-stopped
